### ISSUE TITLE
Memgraph doesn't respect to Index Hinting

### ISSUE THREAD

**Issue by erfansahaf** [memgraph/memgraph#1592] opened 2023-12-17 11:15 UTC
**Memgraph version**
2.13.0

**Environment**
CentOS 7

**Describe the bug**
Memgraph doesn't consider using the Index that is instructed to be used with `USING INDEX`.

**To Reproduce**
I have about 14 million nodes with Device label (`id` property is indexed) and about 50 thousand nodes with Topic label (`id` property is indexed). When I run the following command, the planner decides to use `Device (id)` index instead of `Topic (id)` index:

```
USING INDEX :Topic(id) MATCH (d:Device)-[:SUBSCRIBE]->(t:Topic) WHERE t.id IN ['testDevices'] AND d.id > '0' RETURN d.token, d.platform LIMIT 10000;
```

Query Plan:
```
memgraph> EXPLAIN USING INDEX :Topic(id) MATCH (d:Device)-[:SUBSCRIBE]->(t:Topic) WHERE t.id IN ['testDevices'] AND d.id > '0' RETURN d.token, d.platform LIMIT 10000;
+---------------------------------------------------+
| QUERY PLAN                                        |
+---------------------------------------------------+
| " * Limit"                                        |
| " * Produce {d.token, d.platform}"                |
| " * Filter (t :Topic), {t.id}"                    |
| " * Expand (d)-[anon1:SUBSCRIBE]->(t)"            |
| " * ScanAllByLabelPropertyRange (d :Device {id})" |
| " * Once"                                         |
+---------------------------------------------------+
```

**Expected behavior**
I expect the planner to use `Topic (id)` index:

```
+--------------------------------------------------+
| QUERY PLAN                                       |
+--------------------------------------------------+
| " * Limit"                                       |
| " * Produce {d.token, d.platform}"               |
| " * Filter (d :Device)"                          |
| " * Expand (t)<-[anon1:SUBSCRIBE]-(d)"           |
| " * ScanAllByLabelPropertyValue (t :Topic {id})" |
| " * Unwind"                                      |
| " * Once"                                        |
+--------------------------------------------------+
```

**Comment by katarinasupe** [comment] 2023-12-17 11:26
Hi @erfansahaf, thank you for reporting this 🙏 
Did you notice this happening in other cases or just in this kind of query? How much does this currently affect your workflow? Is this potential bug slowing things down for you, and is it a blocker for you using Memgraph?

**Comment by erfansahaf** [comment] 2023-12-17 11:33
@katarinasupe Since response time is important in our system, the answer is **yes**. It's a blocking issue that leads the system to work slower. Device nodes are about 14 million and this query takes about 2 minutes to run.

**Comment by katarinasupe** [comment] 2023-12-17 11:45
Are you running Memgraph in production? 
Is there a way in your setup to force Memgraph to use the Topic(id) index in this case (e.g., dropping the Device(id) index) as a workaround?

**Comment by erfansahaf** [comment] 2023-12-17 11:49
@katarinasupe

1. Yes we are running Memgraph in Production.
2. Not at all, we need the `Device(id)` index too. 

In this scenario, the best approach is to filter records that are subscribed to a specific topic first, and then, filter again by `Device(id)` range. With this, the query time should be under one second.

**Comment by katarinasupe** [comment] 2023-12-17 12:16
@erfansahaf, I tagged the issue with appropriate labels, which will be looked at by our team resolving community issues. I will keep you updated on the fix.  Here, you'll also be able to see the progress in terms of milestones.
I know the consequences you're experiencing because of this bug, and to help, I can offer you a call with the engineer who initially worked on index hinting. He will understand the problem better and might give you a good hint on how to get the best performance until this bug is fixed for your use case. If you're interested, please [book a call here](https://calendly.com/d/5dm-pbj-dw2/meet-with-me).

**Comment by DavIvek** [comment] 2023-12-22 16:21
It looks to me that the issue is in the planner and optimizer. The problem is that even if the user gives a hint to memgraph's planner which index to use, memgraph will still generate multiple plans (with the user's hint included) and compare their costs based on its query cost estimator. I guess that is not the desired behaviour so I'll look into how to resolve this issue.

**Closed** 2024-01-11 09:10 UTC
Labels: bug, Importance - I2, community, Effort - Medium, Severity - S1

**Comment by karmenrabar** [comment] 2024-01-29 10:23
Hi @erfansahaf, I'm happy to update you that Memgraph has a new release, 2.14., which includes the fix for this issue. We post all of our release updates on Discord, here's the [link](https://discord.com/channels/842007348272169002/1047507324555767858/1200107892968271956) - feel free to join if you already haven't. :)
Could you check if the newest version works as expected for you now?
