### ISSUE TITLE
Connection was closed by server on text regex search

### ISSUE THREAD

**Issue by fabricioereche** [memgraph/memgraph#2311] opened 2024-09-06 19:45 UTC
**Memgraph version**
Memgraph v2.18.1

**Environment**
Container on Docker Desktop (Windows 11 Home Single Language, WSL 2.2.4.0)

**Describe the bug**
When running a regex search the memgraph database breaks

**To Reproduce**
1. Run the following query 'MATCH (i:Insight) WHERE  toUpper(i.\`text\`) =~ '.\*PHASE.\*' return i.srid'

**Expected behavior**
Should return some data without breaking the service

**Logs**
It break down without logs

**Additional context**
Insight node has 41846 register on it and 6299 nodes that contains PHASE on it (changing the regex search to CONTAINS returns correctly).
The issue is replicated using memgraph lab query builder and also using neo4j driver for typescript (nextjs app)

**Comment by as51340** [comment] 2024-12-11 10:23
Hi @fabricioereche I couldn't reproduce the issue. I tried creating 90k nodes without word phase in the text property and 10k nodes with phase in the text property but it never failed. I tried it with python and js driver.

Closing the issue for now, if you reproduce it, open it again. Thanks!

**Closed by as51340** 2024-12-11 10:23 UTC
Labels: bug, community, Effort - Medium, Severity - S1, Priority - Now, Frequency - Daily, Reach - VeryFew
