### ISSUE TITLE
Add pattern comprehension

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#1565] opened 2023-12-06 09:25 UTC
Pattern comprehension needs to be added in order to reduce the number of matches provided by the workaround of the `OPTIONAL MATCH`. 

Usage example:

`CREATE
  (keanu:Person {name: 'Keanu Reeves'}),
  (johnnyMnemonic:Movie {title: 'Johnny Mnemonic', released: 1995}),
  (theMatrixRevolutions:Movie {title: 'The Matrix Revolutions', released: 2003}),
  (theMatrixReloaded:Movie {title: 'The Matrix Reloaded', released: 2003}),
  (theReplacements:Movie {title: 'The Replacements', released: 2000}),
  (theMatrix:Movie {title: 'The Matrix', released: 1999}),
  (theDevilsAdvocate:Movie {title: 'The Devils Advocate', released: 1997}),
  (theMatrixResurrections:Movie {title: 'The Matrix Resurrections', released: 2021}),
  (keanu)-[:ACTED_IN]->(johnnyMnemonic),
  (keanu)-[:ACTED_IN]->(theMatrixRevolutions),
  (keanu)-[:ACTED_IN]->(theMatrixReloaded),
  (keanu)-[:ACTED_IN]->(theReplacements),
  (keanu)-[:ACTED_IN]->(theMatrix),
  (keanu)-[:ACTED_IN]->(theDevilsAdvocate),
  (keanu)-[:ACTED_IN]->(theMatrixResurrections)`

```
MATCH (keanu:Person {name: 'Keanu Reeves'})
RETURN [(keanu)-->(b:Movie) WHERE b.title CONTAINS 'Matrix' | b.released] AS years
```

More information can be found on https://neo4j.com/docs/cypher-manual/current/values-and-types/lists/#cypher-pattern-comprehension

**Comment by gitbuda** [comment] 2023-12-14 06:08
Closing this issue because it's a duplicate of #1310 (all data moved under that issue)

**Closed by gitbuda** 2023-12-14 06:08 UTC
Labels: Effort - High, Importance - I0, Severity - S2, incremental
