### ISSUE TITLE
Corrupted WAL/Snapshot files

### ISSUE THREAD

**Issue by andrejtonev** [memgraph/memgraph#1369] opened 2023-10-16 16:15 UTC
**Memgraph version**
2.11

**Environment**
Ubuntu 22.04

**Describe the bug**
There are a couple of things going on here.

Tried to close memgraph while at 100% CPU. This caused the last Snapshot to be invalid. It was half the size of previous ones.

We are creating a Snapshot every 5 minutes. We should be retaining 3. 
There are many invalid Snapshots that we keep around and that keep getting opened and checked every 5 minutes. This seems to cause a `too many open files` error and also could be causes us to use up the RAM.
NOTE: Memgraph is idle the whole time (other than creating the snapshots).

After one of the crashes, the snapshot/wal was invalid and kept causes a critical error. Log below.
```
[2023-10-10 18:17:28.687] [memgraph_log] [warning] Found a corrupt snapshot file "/var/lib/memgraph/snapshots/20230920140500065767_timestamp_425155742" becuase of: Invalid snapshot data!
[2023-10-10 18:18:08.146] [memgraph_log] [error] Listener failed on accept: Too many open files
[2023-10-10 18:18:37.982] [memgraph_log] [critical] 
Assertion failed in file /memgraph/src/utils/file.cpp at line 346.
	Expression: 'fd_ != -1'ion failed in file /memgraph/src/utils/file.cpp at line 346.
	Expression: 'fd_ != -1'
	Message: 'While trying to open "/var/lib/memgraph/snapshots/20231010181837982557_timestamp_786807465" for writing an error occured: Too many open files (24)'
[2023-10-10 18:18:50.111] [memgraph_log] [warning] Invalid license key string. To use Enterprise features please set it to a valid string using the following query:
SET DATABASE SETTING "enterprise.license" TO "your-license-key"
[2023-10-10 18:23:27.180] [memgraph_log] [critical] You must have at least one WAL file that contains at least one delta that was created before the snapshot file!
```

**To Reproduce**
Hard to reproduce locally.

**Expected behavior**
Invalid Snapshots should be deleted or skipped. Crashing while writing a WAL or Snapshot should not leave the system in an unrecoverable state. Creating Snapshots while idle should not consume all the ram/open files.

@chrischabot

**Comment by as51340** [comment] 2023-10-20 05:21
My findings:
- if a corrupted snapshot file is found, it will be skipped -> it will print a warning and that's it it will go further.
- I think the issue is that we don't delete corrupted snapshot files.

**Comment by andrejtonev** [comment] 2023-10-20 06:45
The corrupt snapshots may just be a red herring. I think the main issue is the "too many open files" and ram consumption while idle.
The only thing we are doing at that time is creating the snapshots every 5 minutes.

In addition to those problems, we should give users better information about what is going on when failing to recover. Currently the logs aren't helpful. Both when encountering invalid snapshots and wal files.

The logic itself is probably fine, but Chris ended up in a situation where he couldn't startup memgraph due to corrupt snapshots and wal files.

**Comment by as51340** [comment] 2023-10-20 06:47
If we would delete corrupted snapshot and wal file when encountered then I think too many open files wouldn't happen? 
> In addition to those problems, we should give users better information about what is going on when failing to recover. 
> Currently the logs aren't helpful. Both when encountering invalid snapshots and wal files.

agree

**Comment by andrejtonev** [comment] 2023-10-20 07:14
> If we would delete corrupted snapshot and wal file when encountered then I think too many open files wouldn't happen?

We have a couple of corrupted snapshots. We open them, realize something is wrong and close them. At least in theory that's what's happening. We also open a new snapshot, write to it and close it. Not sure where the too many open files is coming from.

**Comment by as51340** [comment] 2023-10-20 09:13
@chrischabot and @andrejtonev  since it is hard to verify whether we have a correct fix or not, could you check whether the linked PR solved the issue? It would be the best if you could do it on the machine on which you encountered the error. 
Also, can you run following commands and paste the output you get:
```bash
sudo cat /etc/systemd/user.conf | grep "DefaultLimitNOFILE"
ulimit -n
ulimit -u
cat /proc/sys/fs/file-max
```

**Comment by as51340** [comment] 2023-10-20 09:34
Additionally, I've put some code on here linked PR that will print the maximum number of files as seen from fnctl (which we use for file management on Linux). On my local machine I've got: `[info] Maximum number of files: 1024`. What do you guys have?

**Comment by as51340** [comment] 2023-10-20 09:53
Error message: `Too many open files (24)`. 24 is I think the error code

I will write here what I observed on my local machine:
I have the maximum number of files 1024 and when starting Memgraph, 4 files are opened immediately.
The only file which is explicitly opened when Memgraph is started is: `/home/andi/Memgraph/mg_data/.lock`
Other opened files are `/dev/pts/2, /dev/pts/2, /dev/pts/2`.

Creating one vertex causes the number of opened files to become 8 but we received the request only for opening wal file.
4 new files are: `socket:[7166417], socket:[7166418], socket:[7166417], socket:[7163564]`
After first snapshot is created, the number of opened files remains 8.

**Comment by as51340** [comment] 2023-11-02 07:45
Corrupted snapshot and wal files don't cause too many opened files error, that's confirmed. Too many opened files is [here](https://github.com/memgraph/memgraph/issues/1440).

This issue will hopefully be resolved with https://github.com/memgraph/memgraph/pull/1385. If needed, we will reopen it later.

**Closed** 2023-11-07 10:37 UTC
Labels: bug, Importance - I1, Effort - Medium, Severity - S2
