### ISSUE TITLE
Pass labels as variables / parameters

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1357] opened 2023-10-12 17:02 UTC

**Comment by katarinasupe** [comment] 2024-02-16 10:12
Related to: https://github.com/memgraph/memgraph/issues/1509

**Comment by DavIvek** [comment] 2024-02-23 12:50
If you mean to pass labels as parameters in the following way:
`MATCH (n:$label) return n;  -- {label: "L1"}`
,then this is closed via [1602](https://github.com/memgraph/memgraph/pull/1602). Otherwise, it's the duplicate of [1509](https://github.com/memgraph/memgraph/issues/1509).

**Closed by DavIvek** 2024-02-23 12:50 UTC
Labels: feature, community
