### ISSUE TITLE
Missing nodes in READ UNCOMMITED

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#857] opened 2023-04-03 12:05 UTC
The full context of the discussion and how this was detected can be found here: 
https://discord.com/channels/842007348272169002/1081009360798503063/1088614421938569348

Here is a short summary: 

The user runs two streams concurrently,  one writing to **nodes** and one writing **edges**. The node id is set to unique. 

The node stream/transform would create cypher like: 

`MERGE (n:Node { id: 42, sourceDb: ‘abc’ }) SET n.a = 1, n.b = 2`

The edge stream/transform would create cypher like:

```
MERGE (n:Node { id: 42 })
MERGE (m:Node { id: 43 })
MERGE (n)-[:EDGE]->(m)
```

During the run, the user is experiencing issues with constraint violations and conflicting transactions. This is expected due to the snapshot isolation level. 

After lowering the isolation level to avoid conflicting transactions and constraint violations, `READ UNCOMMITED ` 10K nodes went missing. I guess the missing nodes should not happen in any case.

To avoid the issue, the user updated stream processing for both of those topics into single transform. In the transform, based on the name of the backing kafka topic, it outputs the same cypher as above. But since it’s always running in the same transaction now, there is no unique constraint violation when trying to merge the same node more than once

**Comment by gitbuda** [comment] 2023-07-21 07:56
@antejavor, quick question, is this critical for v2.10?

**Comment by antejavor** [comment] 2023-07-24 08:35
@gitbuda This was reported by a Memgraph user on Discord, who found another solution to avoid the issue. Since nobody is experiencing this issue, we can skip it for v2.10.

**Comment by DavIvek** [comment] 2024-01-17 13:11
I tried to reproduce this with the latest version of MemgraphDB (2.13). The user had this problem while using streams but since I don't have concrete streams that he used, I tried the next approach that should be equivalent in terms of concurrency:
```
from gqlalchemy import Memgraph
from neo4j import GraphDatabase
import threading

URI = "bolt://localhost:7687"
AUTH = ("", "")

def run2():
    with GraphDatabase.driver(URI, auth=AUTH) as client:
        with client.session(database="memgraph") as session:
            for i in range(1000000):
                try:
                    session.run("MERGE (n:Node {id : $id}) MERGE (m:Node {id : $id1}) MERGE (n)-[:REL]->(m)", id=i, id1=i+1)
                except:
                    pass

def run1():
    with GraphDatabase.driver(URI, auth=AUTH) as client:
        with client.session(database="memgraph") as session:
            for i in range(1000000):
                try:
                    session.run("MERGE (n:Node {id : $id}) set n.propertythatdoesntmatter = $prop, n.prop2 = $prop2", id=i, prop=i+5, prop2=i+7)
                except:
                    pass

thread1 = threading.Thread(target=run1)
thread2 = threading.Thread(target=run2)

thread1.start()
thread2.start()

thread1.join()
thread2.join()
```
He was using constraints on `Node(id)`, so I created it before executing this script.
The only exception I got is `Cannot resolve conflicting transactions`, but this is expected due to Memgraph's optimistic approach to constraint checking.
Apart from this issue, we didn't have another similar issue reported and since I wasn't able to reproduce it, I'll close it.

**Closed by DavIvek** 2024-01-17 13:11 UTC
Labels: bug, Importance - I3, community, Effort - High, Severity - S1
