### ISSUE TITLE
Query failed: Connection was closed by server

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#874] opened 2023-04-12 10:25 UTC
I executed a query on my memgraph database and the connection closed.

memgraph version:2.7.0
operating system: windows 10
API：Cypher version 9
query:SET (CASE WHEN true THEN null END).a = 1
error message:Query failed: Connection was closed by server

**Comment by gitbuda** [comment] 2023-04-15 10:28
@ljhhuxiaoba This is a very nice finding! There is a segmentation fault on the Memgraph side. We'll try to include the fix in the next release.

**Comment by gitbuda** [comment] 2023-09-01 08:09
take a look at the @Ignition comment inside #1175 and figure out the root cause to close this issue

**Comment by ljhhuxiaoba** [comment] 2023-09-24 12:02
Hello, has this problem been fixed?

**Comment by gitbuda** [comment] 2023-09-24 15:18
Hi! This particular issue has been fixed under https://github.com/memgraph/memgraph/pull/1175 but we suspect there are more cases like this, and we have to figure out a proper fix across the board 💪 We plan to start that work soon 😃

**Closed** 2023-09-25 08:15 UTC
Labels: bug, Importance - I3, Effort - Low
