### ISSUE TITLE
Memgraph only makes use of 1 CPU core?

### ISSUE THREAD

**Issue by StephenSorriaux** [memgraph/memgraph#595] opened 2022-10-13 16:18 UTC
**Memgraph version**
Memgraphlab 2.5.0

**Environment**
Docker image https://hub.docker.com/layers/memgraph/memgraph-platform/latest/images/sha256-03b3c0ee9f5b3ea99538c447e927e1569830ef5fbb24be2928688ac392758c97?context=explore

New to Memgraph, installation done following https://memgraph.com/docs/memgraph/how-to-guides/work-with-docker

**Describe the bug**
I am trying to perform an analysis about a dataset (21,148 Nodes, 46,970 Relationships) I generated, and the use of
```
CALL nxalg.betweenness_centrality() YIELD *;
```
triggers the default 600s query timeout (tried using the console and memgraphlab). I noticed in the resource system usage that only 1 CPU is actually used, is this by design (or due to the clients I used)?

![image](https://user-images.githubusercontent.com/16797053/195650068-08923335-5bea-4af8-99d4-878ea22806d8.png)

**To Reproduce**
1. Build a similar dataset as mentioned
2. `CALL nxalg.betweenness_centrality() YIELD *;`
3. Check CPU usage

**Expected behavior**
Most of the CPU cores should be used.

**Additional context**
New to Memgraph (and graph DB), I might miss some basic limitations.

**Comment by antoniofilipovic** [comment] 2022-10-14 19:11
Hi @StephenSorriaux,
yes, @gitbuda, it is parallelizable, and we have implemented the [parallelized betweenness centrality](https://memgraph.com/docs/mage/query-modules/cpp/betweenness-centrality) algorithm in c++ in our mage project. Check our [mage](https://memgraph.com/docs/mage/query-modules/cpp/betweenness-centrality#getdirected-normalized-threads) :mage_man:  docs here, and feel free to test it yourself, and we can discuss the next steps, and how we can help you better. I hope I helped, let me know if you need anything else.

**Comment by Josipmrden** [comment] 2022-12-15 20:20
Hello @StephenSorriaux , can you please update on your status of this issue?

**Comment by gitbuda** [comment] 2023-04-10 11:17
Not a bug. It's by design. Ofc, it should be improved because many queries/workloads might be possible to "parallelize".

**Comment by StephenSorriaux** [comment] 2023-04-10 18:17
Hello,

Thank you all for your awesome insights on the issue and sorry for my late reply. I now have the answers I needed and, if you want, the issue can be  closed!

**Comment by Josipmrden** [comment] 2023-04-14 11:16
@StephenSorriaux thanks for the reply! Will close the issue

**Closed** 2023-04-14 11:16 UTC
Labels: enhancement
