### ISSUE TITLE
Write queries impact the read performance of Memgraph 

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1637] opened 2024-01-11 12:58 UTC
**Memgraph version**
Memgraph v2.13 

**Environment**
Docker 

**Describe the bug**
There is a possibility that we have a bug that causes the slower read performance, which could be triggered by separate thread writing to Memgraph. 

**To Reproduce**
1/ Start memgraph instance
`docker run –-rm -p 7687:7687 -p 7444:7444 --name memgraph memgraph/memgraph:2.13.0`

2/ Prepare data
```
UNWIND range(0, 500000) AS id CREATE (n:Node:NodeA {compoundKey: id});
UNWIND range(0, 500000) AS id CREATE (n:Node:NodeB {compoundKey: id});

CREATE INDEX ON :Node(compoundKey); CREATE INDEX ON :Node;
CREATE INDEX ON :NodeA(compoundKey); CREATE INDEX ON :NodeA;
CREATE INDEX ON :NodeB(compoundKey); CREATE INDEX ON :NodeB;

UNWIND range(0, 500000) AS id
MATCH (n:NodeA {compoundKey: id})
MATCH (n1:NodeB {compoundKey: id})
CREATE (n)-[:rel]->(n1);

UNWIND range(0, 10) as id
WITH id
UNWIND range(0, 10000) as relId
MATCH (n:NodeA {compoundKey: id})
MATCH (n1:NodeB {compoundKey: relId})
CREATE (n)-[:rel]->(n1);
```

3/ Run python script
`python3 query-test.py | sort -r | head -n 50`

![image](https://github.com/memgraph/memgraph/assets/18125448/253eae29-0a09-438c-80f8-c3de3b275b10)

```
from concurrent.futures import ThreadPoolExecutor
from subprocess import Popen, PIPE, STDOUT
from threading import Lock
import time, random


MGCONSOLE_BIN_PATH = "./mgconsole-bin"


def write_query(query):
    p = Popen([MGCONSOLE_BIN_PATH, "-username", "", "-password", ""], stdout=PIPE, stdin=PIPE, stderr=STDOUT)

    for i in range(20):
        p.stdin.write(query.replace(b"{id}", str(random.randint(200000, 300000)).encode() ))
        p.stdin.flush()

        time.sleep(5)

    p.terminate()


def run_query(lock, query, query_count):
    p = Popen([MGCONSOLE_BIN_PATH, "-username", "", "-password", ""], stdout=PIPE, stdin=PIPE, stderr=STDOUT)

    for i in range(query_count):
        s = time.time()
        p.stdin.write(query.replace(b"{id}", str(random.randint(0, 1000)).encode() ))
        p.stdin.flush()

        for _ in range(3):
            p.stdout.readline()

        while True:
            r = p.stdout.readline().decode().rstrip()
            if r[-8:] == "-------+":
                break

        with lock:
            print(f"elapsedTime: {time.time()-s}")
        time.sleep(0.01)

    p.terminate()

queries = [
    b'MATCH (c:NodeB) MATCH (c_0:NodeA)-[r_0*1..3]->(c) WHERE c_0.compoundKey = {id} RETURN COUNT(DISTINCT c) AS total;\n',
    b"MATCH (o:Node) WHERE o.compoundKey < {id} RETURN count(o);\n",
    b"MATCH (o:Node) WHERE o.compoundKey = {id} RETURN o;\n",
]

update_queries = [
    b"MATCH (n:NodeA {compoundKey: {id}}) SET n.a = \"test\";\n",
    b"MATCH (n:NodeB {compoundKey: {id}}) SET n.a = \"test\";\n",
]

lock = Lock()
worker_count = len(queries) + len(update_queries)

with ThreadPoolExecutor(max_workers=worker_count) as executor:
    for query in update_queries:
        executor.submit(write_query, query)
    for query in queries:
        executor.submit(run_query, lock, query, 10000)
        
```

If you comment this at line 59-60, you will have stable query time.
![image](https://github.com/memgraph/memgraph/assets/18125448/d53da590-3396-4964-8e37-d07b37e0698b)

**Expected behavior**
Read performance should not be impacted but it is 40x slower in some cases. This means if we have a complex read query that takes around 100ms normally, could turn into the 4-second read query in some cases. 

**Additional context**
This needs to be verified and explored.

**Comment by imilinovic** [comment] 2024-02-20 11:57
While verifying this I've found the following:

1. On the latest version both versions (the uncommented write query and commented write query) had roughly the same speed.
2. Creating indexes at the beginning of the query instead of after the first two queries made them both behave normally with no slow times.
3. For some reason profiling with valgrind didn't work as the python script just got stuck
4. In debug mode I also got the same results as 1. but as it is debug mode everything was just very slow and the queries never finished
5. In the original query, the python queries got slower after the creation of the index

Due to 1. and 2. I'd say there is probably no issue regarding write queries impacting read performance. The slow performance is probably due to having no index and then index being created while new queries are also being executed.

I'll leave the issue open so someone else can verify/disprove this.

**Comment by rkaira-uptycs** [comment] 2024-02-22 11:03
+1

**Comment by rkaira-uptycs** [comment] 2024-02-22 11:06
Even we are facing a similar problem in our environments. Earlier we used to run on 2.8 versions without any issues. Still, after the upgrade to 2.14, we see lots of timeout issues and very slow write queries. The fundamental problem is, even though we set the isolation level to READ_UNCOMMITED. Still, it does not honor the isolation and locks the read records

**Comment by imilinovic** [comment] 2024-02-27 23:18
Comparing the two versions there is indeed a difference. Will revisit

**Comment by imilinovic** [comment] 2024-02-28 09:59
After short investigation I'm pretty sure this started after this [PR](https://github.com/memgraph/memgraph/pull/1361/files). Running the code above on docker 2.11 read & write -> similar query times. After this PR it seems to slow down a lot sometimes. Weird thing is trying the above code on docker 2.11 works but if you build it locally it won't work because of conflicting transactions.

**Comment by katarinasupe** [comment] 2024-03-14 08:23
Frequency is raised because this issue will occur every time there is parallel read and write queries.

**Comment by andrejtonev** [comment] 2024-12-11 09:33
Tested on v2.22, local build. Seeing no difference in performance with or without writes.
Closing since it is not reproducible on newest version.

**Closed by andrejtonev** 2024-12-11 09:33 UTC
Labels: bug, needs triage, needs verification, community, Effort - High, Severity - S2, Priority - Now, Frequency - EveryTime, Reach - Everyone
