### ISSUE TITLE
dateTime() function is missing for handling datetime values with a timezone

### ISSUE THREAD

**Issue by david-sitsky** [memgraph/memgraph#612] opened 2022-10-23 01:10 UTC
I wrote about this issue here: https://discourse.memgraph.com/t/support-for-datetime-function-in-cypher/327/2 but it was suggested I report it here.

I have been trying out memgraph and I have Kafka records written in JSON format. I have been able to import the data successfully and have a “transformation” that reads it and runs the Cypher query per Kafka record successfully to create my graph data.

I have JSON properties written in a common “ISO date-time” format, for example:

2003-01-16T06:59:32.000Z

I can see memgraph’s Cypher has a localDateTime() function, but not a dateTime() function like in Neo4J. Is there a reason for this?

**Comment by katarinasupe** [comment] 2022-10-25 07:31
Thank you @david-sitsky for opening the issue here 😄

**Comment by gitbuda** [comment] 2022-11-17 13:17
@david-sitsky when we designed the feature, all our use cases but also the current ones don't need the timezone part (I think that's the issue here?) + we actually have an optimization on the storage side which is possible because of that. I'm not saying it's not possible to add another data type, but would like to understand the actual need first 😄 

Is it possible from your perspective to use the `localDateTime()` as an alternative to the `dateTime()`?

Thanks for reporting and let's figure out what's the best here 😄

**Comment by david-sitsky** [comment] 2022-11-18 07:12
Hi Marko - worst case I can use localDateTime() for now.

**Comment by Josipmrden** [comment] 2022-12-15 20:18
Can I close this @gitbuda ?

**Comment by PrivateGER** [comment] 2023-04-08 19:44
The thing I'm facing here is that it's impossible to migrate Neo4j data that used DateTime() without an external python convert script.

This issue should *really* be mentioned in your https://memgraph.com/blog/how-to-migrate-from-neo4j-to-memgraph article.

**Comment by katarinasupe** [comment] 2023-04-14 08:28
Hi @PrivateGER, thanks for pointing this out. We will create a **migration guide** on our documentation to avoid such issues. The blog post talked about one way of migrating your data, and I recommend you [join our Discord server](https://www.discord.gg/memgraph), if you haven't, so that we can better help you in the process of migration. Currently, users reported that the best way to migrate their data was to either have their dataset in CSV files and import it with [LOAD CSV clause](https://memgraph.com/docs/memgraph/import-data/load-csv-clause) in Memgraph, or by exporting all data from Neo4j in a file that consist of cypher queries (cypherl file), changing it a bit (a bit different syntax for constraints and indexes) and [importing it into Memgraph via mgconsole or Memgraph Lab](https://memgraph.com/docs/memgraph/import-data/files/cypherl). 

Kudos to the community member for sharing these tips:

> To migrate, use this command on Neo4j:
> `call apoc.export.cypher.all("file_name.cypherl", {format:"plain", useOptimizations:{type:"NONE"}, writeNodesProperties: true})`
> 
> Go into the generated file and change the constraint creation queries, from:
> `CREATE CONSTRAINT <constraintName> FOR (node:<Label>) REQUIRE (node.<prop>) IS UNIQUE;`
> 
> to
> `CREATE CONSTRAINT ON (node:<Label>) ASSERT node.<prop> IS UNIQUE`
> 
> Since both engines use a different syntax.
> After that, import the .cypherl file into Memgraph.
> 
> Now, some changes might be required if you have multiple databases or models. But then you should just make some changes in the `apoc.export.cypher.all` configuration parameters.
> 

The user was able to do this to a single instance of Neo4j, with only one model. They only had [uniqueness constraints](https://memgraph.com/docs/memgraph/next/how-to-guides/constraints/uniqueness-constraint). Here are [the docs](https://memgraph.com/docs/memgraph/next/how-to-guides/constraints/existence-constraint ) for the existence constraint syntax in Memgraph.
Be careful, and please also [create indexes](https://memgraph.com/docs/memgraph/how-to-guides/indexes) before importing data into Memgraph. If you are using cypherl file, add lines at the beginning with index creation. Here are the [tips](https://memgraph.com/docs/memgraph/reference-guide/indexing) on when to create indexes.

**Comment by Josipmrden** [comment] 2023-04-14 09:35
Hey @PrivateGER, to get to the issue again. Is it the case that Neo4j supports a timezone part in its database types and we don't?

And what does your external script do in order to mitigate the issue?

**Comment by katarinasupe** [comment] 2023-04-14 09:47
The issue is there is no temporal type in Memgraph which supports timezone. For example, here are the steps to reproduce the issue if we try creating a relationship with a `LocalDateTime` property:

Run query:
`CREATE (u:User)-[:CREATED {createdAt: localDateTime("2003-01-16T06:59:32.000")}]->(p:Post)`

Here is what you get in Memgraph:

![Screenshot 2023-04-14 at 11 41 35](https://user-images.githubusercontent.com/61758502/232009927-991b9053-f474-42b3-9daa-1ce69b4d1dce.png)

This happens because `LocalDateTime` type does not support ending Z which indicates that that time is UTC.

**Comment by PrivateGER** [comment] 2023-04-15 15:15
@katarinasupe got it right. 

My script simply parsed the CSV file, took the RFC 3339 timestamps, and converted them. I didn't go with Memgraph for different reasons this time, but may in the future.

**Comment by coryvirok** [comment] 2023-07-11 03:19
I'll add my support for including non-local datetime. Without it, we need to store the datetime as a UNIX timestamp alongside a timezone field. Assuming local time is a non-starter especially in a cloud environment where we do not know what the server's local timezone is set to.

Thanks

**Comment by katarinasupe** [comment] 2023-07-11 10:44
Hi @coryvirok, thanks for adding your support. As you can see, we added a higher impact to this feature. Did you maybe try some workaround for now? Are you streaming data into the database? I am just trying to figure out how large of a blocker this is for you to prioritize better. Btw. feel free to [join our Discord server](https://www.discord.gg/memgraph) if you'd like to talk more since the communication should be easier there 😄

**Comment by coryvirok** [comment] 2023-07-12 01:09
I'm still in early phases of deciding between Graph DBs but I ran into this while building a test schema. I can work around it for now, but if I was already using Neo4J this would have been a blocker to using Memgraph as a "drop in replacement" like I see messaged on the website. Thanks for your response.

**Comment by Josipmrden** [comment] 2023-07-17 06:04
@antoniofilipovic please read this so we can see what to do
@gitbuda also

**Comment by matea16** [comment] 2024-01-23 14:55
[+1 from the community](https://github.com/memgraph/gqlalchemy/issues/300)

**Closed** 2024-05-02 15:01 UTC
Labels: feature, Effort - Unknown, Severity - S3, customer, Frequency - EveryTime, Reach - Most
