### ISSUE TITLE
Add geospatial datatype support

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1290] opened 2023-09-23 00:01 UTC

**Comment by matea16** [comment] 2023-12-12 10:54
+1 on the issue from the user on [Discord](https://discord.com/channels/842007348272169002/890968055339958292/1182677054743920692) who requested a POINT type

**Comment by antejavor** [comment] 2023-12-13 10:41
This is directly related: https://github.com/memgraph/memgraph/issues/1583

**Comment by DavIvek** [comment] 2024-02-23 11:57
Duplicate of [1583](https://github.com/memgraph/memgraph/issues/1583)

**Closed by DavIvek** 2024-02-23 11:57 UTC
Labels: feature, Importance - I3, community, Effort - Unknown, Severity - S2, geospatial
