### ISSUE TITLE
Neo4j Go driver fails with panic: invalid state 4, expected: [0] (Constraints) 

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1441] opened 2023-10-31 12:43 UTC
**Memgraph version**
Memgraph docker 2.11

**Describe the bug**
Memgraph and Neo4j Go driver communication fail with the following panic message: 

panic: invalid state 4, expected: [0]

**To Reproduce**
```
package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/db"
)

type SingleResTransformer struct {
}

// Accept implements neo4j.ResultTransformer.
func (*SingleResTransformer) Accept(rec *db.Record) error {
	if len(rec.Values) != 1 {
		return errors.New("expected 1 value")
	}
	return nil
}

// Complete implements neo4j.ResultTransformer.
func (*SingleResTransformer) Complete(keys []string, summary neo4j.ResultSummary) (bool, error) {
	return true, nil
}

func main() {

	dbUser := ""
	dbPassword := ""
	dbUri := "bolt://localhost:7687" // scheme://host(:port) (default port is 7687)
	driver, err := neo4j.NewDriverWithContext(dbUri, neo4j.BasicAuth(dbUser, dbPassword, ""))
	ctx := context.Background()
	defer driver.Close(ctx)

	err = driver.VerifyConnectivity(ctx)
	if err != nil {
		panic(err)
	} else {
		fmt.Println("Viola! Connected to Memgraph!")
	}

	session := driver.NewSession(ctx, neo4j.SessionConfig{DatabaseName: "memgraph"})
	// Create a unique constraint on project name
	 query := "CREATE CONSTRAINT ON (p:Project) ASSERT p.name IS UNIQUE;"
	 _, err = session.Run(ctx, query, nil)
	 if err != nil {
		panic(err)
	}
	session.Close(ctx)

	Create multiple projects nodes
	projects := []string{
		"Neo4j",
		"ArangoDB",
		"MongoDB",
		"PostgreSQL",
		"MySQL",
		"MariaDB",
		"Oracle",
	}

	actQuery := `CREATE (p:Project {name: $project}) 
	RETURN p
	`

	for _, project := range projects {
		records, err := neo4j.ExecuteQuery(ctx, driver, actQuery, map[string]any{"project": string(project)}, func() neo4j.ResultTransformer[bool] {
			return &SingleResTransformer{}
		})
		if err != nil {
			panic(err)
		} else {
			fmt.Println(records)
		}

	}
}
```
**Expected behavior**
On the first run, everything works; once the constraint error is hit, the connection fails. 
panic: invalid state 4, expected: [0]

**Logs**
On the first run, everything works, as it should. 

```
[2023-10-31 12:26:16.748] [memgraph_log] [info] Accepted a connection from Bolt: 192.168.65.1:52610
[2023-10-31 12:26:16.749] [memgraph_log] [info] Using version 5.2 of protocol
[2023-10-31 12:26:16.749] [memgraph_log] [info] Client connected 'Go Driver/5.14.0'
[2023-10-31 12:26:16.750] [memgraph_log] [debug] [Run - memgraph] 'CREATE (p:Project {name: $project})
	RETURN p
	'
[2023-10-31 12:26:16.750] [memgraph_log] [trace] PrepareCypher has not encountered all shortest paths and will  use of monotonic memory
[2023-10-31 12:26:16.750] [memgraph_log] [trace] Error message: Unable to commit due to unique constraint violation on :Project(name)
[2023-10-31 12:26:16.751] [memgraph_log] [trace] Reset received
[2023-10-31 12:26:18.695] [memgraph_log] [info] Bolt client 192.168.65.1:52610 closed the connection.
[2023-10-31 12:26:18.695] [memgraph_log] [error] Session shutdown failed: Transport endpoint is not connected [system:107]
```

**Comment by as51340** [comment] 2023-11-02 07:27
Cannot reproduce with go 1.18, Neo4j-go driver 5.14 and Memgraph Docker 2.11, which go version did you use?

**Comment by M1K8** [comment] 2023-11-02 11:30
I encountered this issue using 1.21.3

**Comment by antejavor** [comment] 2023-11-02 11:39
@as51340 Yep, as @M1K8 mentions, only after you got an error that `2023-10-31 12:26:16.750] [memgraph_log] [trace] Error message: Unable to commit due to unique constraint violation on :Project(name)`
So, after the second time running the code from above.

**Comment by as51340** [comment] 2023-11-02 11:45
Yep, had some problems in local env, reproduced now :+1:

**Comment by as51340** [comment] 2023-11-02 11:53
But I think it is expected that the clients disconnects once the constraint error is hit since you are doing `panic(err)`.?

**Comment by as51340** [comment] 2023-11-02 11:55
And then since you do panic, this causes go client to exit and Memgraph prints warnings:
```bash
Session error: Connection reset ...
Session shutdown failed: ...

```

**Comment by M1K8** [comment] 2023-11-02 12:07
In my use case, any subsequent queries fail with the reported error code, or referencing an 'unexpected RECORD response'.

**Comment by as51340** [comment] 2023-11-03 07:21
Can you give me concrete example where you observe that client cannot query any further? If I modify your code like this:
```go
package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/db"
)

type SingleResTransformer struct {
}

// Accept implements neo4j.ResultTransformer.
func (*SingleResTransformer) Accept(rec *db.Record) error {
	if len(rec.Values) != 1 {
		return errors.New("expected 1 value")
	}
	return nil
}

// Complete implements neo4j.ResultTransformer.
func (*SingleResTransformer) Complete(keys []string, summary neo4j.ResultSummary) (string, error) {
	return "Created project", nil
}

func main() {

	dbUser := ""
	dbPassword := ""
	dbUri := "bolt://localhost:7687" // scheme://host(:port) (default port is 7687)
	driver, err := neo4j.NewDriverWithContext(dbUri, neo4j.BasicAuth(dbUser, dbPassword, ""))
	ctx := context.Background()
	defer driver.Close(ctx)

	err = driver.VerifyConnectivity(ctx)
	if err != nil {
		panic(err)
	} else {
		fmt.Println("Viola! Connected to Memgraph!")
	}

	session := driver.NewSession(ctx, neo4j.SessionConfig{DatabaseName: "memgraph"})
	// Create a unique constraint on project name
	 query := "CREATE CONSTRAINT ON (p:Project) ASSERT p.name IS UNIQUE;"
	 _, err = session.Run(ctx, query, nil)
	 if err != nil {
		panic(err)
	}
	session.Close(ctx)

  // Create multiple projects nodes
	projects := []string{
		"Neo4j",
		"ArangoDB",
		"MongoDB",
		"PostgreSQL",
		"MySQL",
		"MariaDB",
		"Oracle",
	}

	actQuery := `CREATE (p:Project {name: $project}) 
	RETURN p
	`

	for _, project := range projects {
		records, err := neo4j.ExecuteQuery(ctx, driver, actQuery, map[string]any{"project": string(project)}, func() neo4j.ResultTransformer[string] {
			return &SingleResTransformer{}
		})
		if err != nil {
      fmt.Println("Constraint not satisfied")
      query := "CREATE (n:Node {id: 10});"
      _, err = session.Run(ctx, query, nil)
      if err != nil {
        fmt.Println("Couldn't create fallback node")  
      } else {
        fmt.Println("Node successfully created")
      }
		} else {
			fmt.Println(records)
		}

	}
  fmt.Println("Finished running script")

}
```
Then client can create new nodes. However, you should still see an error at the end when the go script finishes.

**Comment by as51340** [comment] 2023-11-03 07:40
Can you verify this is the case?

**Comment by M1K8** [comment] 2023-11-03 08:55
In my case, new nodes are not created

**Comment by as51340** [comment] 2023-11-03 10:21
Understand. This issue is most probably related to #1162 and there is maybe some other. First step will be resolving #1162 and then we get back to this to see if the issue still persists.

**Comment by DavIvek** [comment] 2024-01-10 11:13
It looks to me that this is fixed.
@M1K8 do you still have the same issue with the newest version of memgraph?

**Comment by as51340** [comment] 2024-01-10 12:49
IMO this should be fixed @DavIvek, @antepusic worked on this. Can you guys verify?

**Comment by DavIvek** [comment] 2024-01-10 12:57
@as51340 I tried to reproduce this with the script you proposed earlier. After a constraint error occurs, I can create new nodes and memgraph isn't in an invalid state.

**Closed** 2024-01-23 18:27 UTC
Labels: bug, Importance - I2, community, Effort - Medium, Severity - S2
