### ISSUE TITLE
Query crashes Memgraph because it can't generate a valid plan

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#2491] opened 2024-11-21 08:12 UTC
**Memgraph version**
v2.21.0

**Environment**
Docker

**Describe the bug**
The following query crashes Memgraph
```
MATCH (d_1)-[l_4]->(hyc_1)
WITH *
MATCH (d_4)-[l_5]->(hyc_1)
WITH *
MATCH (d_2)-[l_6]->(h_2)
WITH *
MATCH (d_5)-[l_7]->(h_2)
CALL {
  MATCH (d_1)-[]->(i)-[]-()<-[]-(hyc_1)
  RETURN 1 as i_1
}
CALL {
  WITH d_4, hyc_1
  MATCH (d_4)-[]->(i)-[]-()<-[]-(hyc_1)
  RETURN 1 as i_2
}
RETURN 1;
```

**To Reproduce**
Just run Memgraph with the query above

**Expected behavior**
The query should generate a valid plan at least once

**Logs**
```
[2024-11-21 09:10:25.289] [memgraph_log] [critical] 
Assertion failed in file  at line 155.
        Expression: 'valid_plan_found'
        Message: 'Could not create a valid query plan!'
```

**Comment by Ignition** [comment] 2024-11-27 14:08
Some investigation the problem is around:
```
CALL {
// BUG around (anonA)<-[anonB]-(hyc_1)
// the code detects anonA isn't bound so opts for edge scan for anonB
MATCH (d_1)-[]->(i)-[]-()<-[]-(hyc_1)
RETURN 1 as i_1
}
```
With all the WITH * there are no pattern variations, just one deterministic variation which makes a ScanByEdgeType which is invalid (no edge index it replace it with).

I feel the variable start code is wrong and don't account for the alternative permutations of `(d_1)-[]->(i), (i)-[]-(anon), (anon)<-[]-(hyc_1)`
FYI a `WITH d_1, hyc_1` inside the call, it avoids the issue...I assume that fixes the variable start issue....but I'm not sure why.

This kind of issue would also be fixed with an equality saturation approach. Issue here is that we do one substitution which leads to a dead end plan, alternative substitution would have yielded a valid plan.

**Comment by gitbuda** [comment] 2024-12-11 09:05
Yea, this is a deeper issue, @Ignition proposed that the proper way of detecting this should be the the plan analysis and detecting there is a problem. The best quick fix is to throw instead of crashing Memgraph.

**Closed** 2024-12-13 10:34 UTC
Labels: bug, Effort - Medium, Severity - S2, customer, Priority - Later, Frequency - EveryTime, Reach - Some, Capability - planner
