### ISSUE TITLE
Optimize filter expression if a large params map is used

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1624] opened 2024-01-08 20:09 UTC
If a large map is used in a query like:
```
WITH "1" as a WHERE $key!= Null
RETURN a;
```
latency seems to be fine, on the other hand, if a query like the following one is used:
```
WITH "1" as a WHERE $key!= Null
WITH "1" as a WHERE $key!= Null
WITH "1" as a WHERE $key!= Null
WITH "1" as a WHERE $key!= Null
WITH "1" as a WHERE $key!= Null
RETURN a;
```
the execution time is ~50% slower, but during traversals that's amplified many many times.

NOTE: the params map is just ~5MB

**Comment by Josipmrden** [comment] 2024-01-25 10:05
So basically first thing that is wrong in this query is that no matter how many of them are applied, `!= null` is actually equal to null in most databases so this operation is invalid. The query should be something like `WHERE $key is not null` so it's a valid query execution.

**Comment by Josipmrden** [comment] 2024-02-28 08:19
@gitbuda Workaround found by the customer, can we close this issue?

**Comment by Josipmrden** [comment] 2024-05-15 10:04
Reopened because C++ query modules are being congested by a unique lock.

**Comment by antepusic** [comment] 2024-06-10 12:32
@Josipmrden Are there any changes in issue description now that it’s reopened? For one, I’d like to know which query modules are implicated in it, and whether the crux of the issue is now filtering performance or the existence of the unique lock.

**Closed** 2024-11-21 08:42 UTC
Labels: optimization, Effort - High, Severity - S1, customer, Priority - Now, Frequency - EveryTime, Reach - Everyone
