### ISSUE TITLE
SHOW TRANSACTIONS hangs on the long running LOAD CSV

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#884] opened 2023-04-17 17:00 UTC
@antoniofilipovic, please attach more info once you can recreate it 🙏

**Comment by katarinasupe** [comment] 2023-06-07 12:32
@antoniofilipovic any update on this issue?

**Comment by as51340** [comment] 2023-06-12 08:57
Yes, I couldn't recreate the issue several times so not sure what is happening. I think we can close this issue for now and reopen it if someone manages to recreate.

**Comment by katarinasupe** [comment] 2023-06-12 08:59
Closing for now since we did not manage to reproduce. We will reopen it if there are more reports like this one.

**Closed by katarinasupe** 2023-06-12 08:59 UTC
Labels: bug
