### ISSUE TITLE
Memgraph v2.12.1 Fails to Start on Ubuntu 22.04.2 via WSL

### ISSUE THREAD

**Issue by kgolubic** [memgraph/memgraph#1551] opened 2023-11-30 10:50 UTC
**Memgraph version**
Memgraph v2.12.1 for Ubuntu downloaded from https://download.memgraph.com/memgraph/v2.12.1/ubuntu-22.04/memgraph_2.12.1-1_amd64.deb

**Environment**
Windows 11, Microsoft Windows [Version 10.0.22631.2715](https://support.microsoft.com/en-au/topic/november-14-2023-kb5032190-os-builds-22621-2715-and-22631-2715-f9e3e13c-5e98-42c2-add8-f075841ca812), WSL2

**Describe the bug**

**To Reproduce**
1. Open PS in admin mode.
2.  `wsl --unregister Ubuntu `
3.  `wsl --install -> this has installed Ubuntu 22.04.2 LTS `
4.  `sudo apt update `
5.  `sudo apt upgrade `
6.  `wget https://download.memgraph.com/memgraph/v2.12.1/ubuntu-22.04/memgraph_2.12.1-1_amd64.deb `
7.  `sudo dpkg -i memgraph_2.12.1-1_amd64.deb `
8.  `sudo runuser -l memgraph -c '/usr/lib/memgraph/memgraph' `

I get the error:

```
You are running Memgraph v2.12.1
To get started with Memgraph, visit https://memgr.ph/start
Aborted
```

I run `tail /var/log/memgraph/memgraph_2023-11-30.log`

```
  File "/usr/lib/memgraph/query_modules/mgp_networkx.py", line 5, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:24:06.538] [memgraph_log] [warning] Using non-secure Bolt connection (without SSL). For more details, visit https://memgr.ph/ssl.
[2023-11-30 11:24:35.607] [memgraph_log] [critical]
Assertion failed in file /memgraph/src/memgraph.cpp at line 239.
        Expression: 'lock_file_handle.AcquireLock()'
        Message: 'Couldn't acquire lock on the storage directory "/var/lib/memgraph"!
Another Memgraph process is currently running with the same storage directory, please stop it first before starting this process!'
```

I've restated the computer and I tried to run  `sudo runuser -l memgraph -c '/usr/lib/memgraph/memgraph' ` again.

This time I got
```
You are running Memgraph v2.12.1
To get started with Memgraph, visit https://memgr.ph/start
Max virtual memory areas vm.max_map_count 65530 is too low, increase to at least 262144
Aborted
```

The I run: $ `cat /var/log/memgraph/memgraph_2023-11-30.log`
```
[2023-11-30 11:24:06.374] [memgraph_log] [warning] Invalid license key string. To use Enterprise features please set it to a valid string using the following query:
SET DATABASE SETTING "enterprise.license" TO "your-license-key"
[2023-11-30 11:24:06.397] [memgraph_log] [warning] Replication configuration will NOT be stored. When the server restarts, replication state will be forgotten.
[2023-11-30 11:24:06.477] [memgraph_log] [warning] No snapshot or WAL file found. For more details, visit https://memgr.ph/durability.
[2023-11-30 11:24:06.516] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/wcc.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/wcc.py", line 12, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/wcc.py", line 4, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:24:06.520] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/graph_analyzer.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/graph_analyzer.py", line 16, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/graph_analyzer.py", line 8, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:24:06.531] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/nxalg.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/nxalg.py", line 15, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/nxalg.py", line 4, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:24:06.537] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/mgp_networkx.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/mgp_networkx.py", line 13, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/mgp_networkx.py", line 5, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:24:06.538] [memgraph_log] [warning] Using non-secure Bolt connection (without SSL). For more details, visit https://memgr.ph/ssl.
[2023-11-30 11:24:35.607] [memgraph_log] [critical]
Assertion failed in file /memgraph/src/memgraph.cpp at line 239.
        Expression: 'lock_file_handle.AcquireLock()'
        Message: 'Couldn't acquire lock on the storage directory "/var/lib/memgraph"!
Another Memgraph process is currently running with the same storage directory, please stop it first before starting this process!'
[2023-11-30 11:30:58.007] [memgraph_log] [warning] Invalid license key string. To use Enterprise features please set it to a valid string using the following query:
SET DATABASE SETTING "enterprise.license" TO "your-license-key"
[2023-11-30 11:30:58.024] [memgraph_log] [warning] Replication configuration will NOT be stored. When the server restarts, replication state will be forgotten.
[2023-11-30 11:30:58.090] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/wcc.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/wcc.py", line 12, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/wcc.py", line 4, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:30:58.105] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/graph_analyzer.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/graph_analyzer.py", line 16, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/graph_analyzer.py", line 8, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:30:58.114] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/nxalg.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/nxalg.py", line 15, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/nxalg.py", line 4, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:30:58.118] [memgraph_log] [error] Unable to load module "/usr/lib/memgraph/query_modules/mgp_networkx.py"; Traceback (most recent call last):
  File "/usr/lib/memgraph/query_modules/mgp_networkx.py", line 13, in <module>
    raise import_error
  File "/usr/lib/memgraph/query_modules/mgp_networkx.py", line 5, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
. For more details, visit https://memgr.ph/modules.
[2023-11-30 11:30:58.119] [memgraph_log] [warning] Using non-secure Bolt connection (without SSL). For more details, visit https://memgr.ph/ssl.
[2023-11-30 11:31:30.925] [memgraph_log] [critical]
Assertion failed in file /memgraph/src/memgraph.cpp at line 239.
        Expression: 'lock_file_handle.AcquireLock()'
        Message: 'Couldn't acquire lock on the storage directory "/var/lib/memgraph"!
Another Memgraph process is currently running with the same storage directory, please stop it first before starting this process!'
```

**Expected behavior**
Memgraph to star normally.

**Logs**
Included above.

**Additional context**
@antepusic mentioned on internal Slack that he had the same "Max virtual memory areas vm.max_map_count 65530 is too low, increase to at least 262144" issue on pure Ubuntu box.

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
- I need .deb package for Ubuntu 22

**Comment by DavIvek** [comment] 2023-12-17 12:29
@kgolubic It looks to me that the problem is a path to query modules. They are not located under `usr/lib`, it might be that they are located under `usr/local/lib` and that changing the config flag for query modules location could solve the issue.

**Comment by katarinasupe** [comment] 2023-12-22 11:20
@kgolubic can you verify if what @DavIvek suggested resolves the issue and if that's the case document that properly for Ubuntu via WSL users?

**Comment by kgolubic** [comment] 2023-12-22 11:23
Sure I can. I’ll test it and report the results back.

**Comment by kgolubic** [comment] 2023-12-29 14:32
@DavIvek qurey modules are located in `/usr/lib/memgraph/query_modules/`

```
kruno@laptop:~$ ls -al /usr/local/lib/
total 12
drwxr-xr-x  3 root root 4096 Nov 22 22:36 .
drwxr-xr-x 10 root root 4096 Nov 22 22:36 ..
drwxr-xr-x  3 root root 4096 Nov 22 22:36 python3.10
kruno@laptop:~$ ls -al /usr/lib/memgraph/query_modules/
total 3244
drwxr-xr-x 3 root root    4096 Dec 29 14:31 .
drwxr-xr-x 5 root root    4096 Dec 29 14:31 ..
-rw-r--r-- 1 root root     151 Nov 10 15:10 convert.py
-rwxr-xr-x 1 root root    8800 Dec  8 11:14 example_c.so
-rwxr-xr-x 1 root root 1531224 Dec  8 11:14 example_cpp.so
-rw-r--r-- 1 root root    9795 Mar 29  2021 graph_analyzer.py
-rw-r--r-- 1 root root    9999 Mar 29  2021 mgp_networkx.py
-rw-r--r-- 1 root root     205 Nov 10 15:10 mgps.py
-rw-r--r-- 1 root root   31533 Mar 29  2021 nxalg.py
-rw-r--r-- 1 root root    4065 Oct  7  2021 py_example.py
-rwxr-xr-x 1 root root 1688344 Dec  8 11:15 schema.so
drwxr-xr-x 2 root root    4096 Dec 29 14:31 src
-rw-r--r-- 1 root root    1964 Mar 29  2021 wcc.py
```

I've made a clean install with Memgraph 2.13.0 but the issue is still the same. I can't run Memgraph inside WSL.

```
kruno@Golubic:~$ sudo runuser -l memgraph -c '/usr/lib/memgraph/memgraph'
[2023-12-29 14:35:26.107] [warning] storage_parallel_index_recovery flag is deprecated. Check storage_mode_parallel_schema_recovery for more details.
[2023-12-29 14:35:26.107] [warning] storage_parallel_index_recovery flag is deprecated. Check storage_mode_parallel_schema_recovery for more details.
You are running Memgraph v2.13.0
To get started with Memgraph, visit https://memgr.ph/start
Aborted
```

**Comment by DavIvek** [comment] 2023-12-29 14:37
Thanks for verifying. I'll check it out.

**Comment by DavIvek** [comment] 2024-01-22 12:41
I was able to reproduce this. When we run `sudo runuser -l memgraph -c '/usr/lib/memgraph/memgraph' ` we get an error because we already have a memgraph process running and that process acquired a lock on `/var/lib/memgraph`. You can either kill that process or change the config file. To kill an already running process you can run `ps aux | grep memgraph` and then kill the process with the given pid. 
I'm not sure which command started memgraph, but I guess it's `sudo dpkg -i memgraph_2.12.1-1_amd64.deb` (I'll check this further). 
We should also update the docs accordingly.

**Comment by DavIvek** [comment] 2024-01-22 15:15
We agreed to update docs, so I'm closing this issue.

**Closed as completed by DavIvek** 2024-01-22 15:15 UTC
Labels: bug, Importance - I3, community, Effort - Medium, Severity - S2
