### ISSUE TITLE
[BUG] Memory usage not aligned with --memory-limit

### ISSUE THREAD

**Issue by jhb** [memgraph/memgraph#745] opened 2023-01-23 15:03 UTC
**Memgraph version**
The 2.6.4-memgraph2.5.1-lab2.4.0-mage1.5.1 docker image. The machine has 64GB Ram.

**Environment**
I am using WSL2 on a windows 10 machine. I issue the query using the neo4j python bolt driver.

**Describe the bug**

memgraph-platform is started with `--memory-limit=2048`, and lab speaks of 2GB available RAM. When deleting lots of data (1m nodes, 3 million edges) htop reports RES to be at 3452MB, with lab talking about 3,4GB of 2GB being used, and top also agrees.

**To Reproduce**

1. Create 1 Million nodes and 3 million random edges between them (each node has 3 random edges)
2. Try do delete them **`MATCH (n:Random) DETACH DELETE n;`**
3. Watch htop/top/lab
4. As a bonus, get `neo4j.exceptions.TransientError: {code: Memgraph.TransientError.MemgraphError.MemgraphError} {message: Memory limit exceeded! Attempting to allocate a chunk of 8B, which would put the current use to 2.18GiB, while the maximum allowed`

**Expected behavior**

Ideally: a really low memory consumption. Alternatively, a clean fail at 2048MB RAM usage.

**Comment by antoniofilipovic** [comment] 2023-01-23 15:35
Hi @jhb,

thanks for reporting the issue. It seems like an apparent bug. Let me ask you a few more follow-up questions. Did you create any additional properties on nodes or edges? Did you try running memgraph natively?


We will inspect it and let you know.

Antonio

**Comment by gitbuda** [comment] 2023-02-23 07:55
If I recall correctly, `DETACH DELETE` has a specific semantic, in addition to figuring out why the memory goes above the limit, we should maybe introduce `DROP DATA;` query 😄

**Comment by antejavor** [comment] 2023-03-24 08:50
The more users on discord are reporting this issue: https://discord.com/channels/842007348272169002/890969266600423504/1088549217385054268

**Comment by gitbuda** [comment] 2023-07-03 08:12
Any test case should go under `tests/e2e/memory`

**Comment by gitbuda** [comment] 2023-07-21 08:11
We need to check/count pages (VIRT is not accurate, RES is accurate) and probably combine that with our counter (an idea)

**Comment by antoniofilipovic** [comment] 2023-09-25 11:42
This bug seems to be fixed with the new [PR](https://github.com/memgraph/memgraph/pull/1250). Tested with memory limit set on 2GiB and tried query which would overflow the limit, it stopped as soon as it reached the limit. 

For now, this will stay open for @steffiindrayani to test once this PR lands on the master.

**Comment by antoniofilipovic** [comment] 2023-09-25 11:51
Was able to reproduce this bug. Without bigger introspection in code, it could be we are not using our jemalloc allocator to allocate vectors or other chunks of memory which results in an issue that memory is not properly tracked. 

When we are [creating nodes and relationships](https://github.com/memgraph/memgraph/issues/1222), the memory limit is respected with [a new fix on PR here](https://github.com/memgraph/memgraph/pull/1250), but here it is not.

**Comment by antoniofilipovic** [comment] 2023-09-25 12:07
Seems like there is an issue in the code on the place where we use detach delete. On the whole code path, we are not using `utils::MemoryTracker::OutOfMemoryExceptionEnabler oom_exception;` which enables us to throw exception. This should be a pretty straightforward fix. Now it works together with the PR I linked.

**Comment by antoniofilipovic** [comment] 2023-10-20 13:48
This PR should fixe issue: https://github.com/memgraph/memgraph/pull/1379

**Closed** 2023-10-25 10:16 UTC
Labels: bug, Importance - I3, memory, DX
