### ISSUE TITLE
Fix simple MERGE with variable causes a big memory spike 

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1251] opened 2023-09-14 13:16 UTC
**Memgraph version**
2.10.1

**Environment**
Memgraph Docker

**Describe the bug**
During the batch execution of the `MERGE` clause from GQL Alchemy, the `MERGE` clause that contains variable for a node will cause a significant memory spike 30x times. . 

**To Reproduce**
Causes an issue: 
```
#Bulk query execution (stopped at 100k nodes). Memory usage notes: start 77MB, end 2.57 GB! After FREE MEMORY 2.55 GB (approximated 6GB for 200k nodes ), after restart 102 MB

memgraph_conn = Memgraph(host='localhost', port=7687, username="", password="")
batch_data = []
batch_size = 300
index = 1
address = 1000
memgraph_conn.execute("CREATE INDEX ON :MyNode(address)")
for i in range(200000):
    s = f"s{str(index)}"
    query = f"MERGE ({s}:MyNode {{address: {address}}})"
    batch_data.append(query)
    index += 1
    address += 1

    if len(batch_data) >= batch_size:
        memgraph_conn.execute("".join(batch_data))
        batch_data = []

```
```
#Bulk query execution without MERGE variable. Memory usage notes: start 77MB, end 212 MB! After restart 126 MB

memgraph_conn = Memgraph(host='localhost', port=7687, username="", password="")
batch_data = []
batch_size = 300
index = 1
address = 1000
memgraph_conn.execute("CREATE INDEX ON :MyNode(address)")
for i in range(200000):
    s = f"s{str(index)}"
    query = f"MERGE (:MyNode {{address: {address}}})"
    batch_data.append(query)
    index += 1
    address += 1

    if len(batch_data) >= batch_size:
        memgraph_conn.execute("".join(batch_data))
        batch_data = []

```

**Expected behavior**
These two workloads should have similar memory usage. 

**Logs**
Not applicable 

**Additional context**
Also, once Memgraph was out of Memroy, there was no warning.

**Comment by antoniofilipovic** [comment] 2023-09-20 10:24
@antejavor these two code blocks are the same, can you check if that is correct?

**Comment by antejavor** [comment] 2023-09-20 10:27
@antoniofilipovic notice the variable next to the `MERGE` clause, it makes all the difference, aldo it should not.

**Comment by antoniofilipovic** [comment] 2023-09-20 10:29
@antejavor thanks, will test with new memgraph 2.11 + jemalloc memory tracker to see what is happening

**Comment by Ignition** [comment] 2023-09-22 08:54
Gut feeling, AFK ATM so I've not read any code to confirm this. I'd expect this to be agnostic of MERGE. 300 variables per frame is quite large.
If a variable exists, we expect it to be used. Hence, ATM no analysis pass to remove unused variable creation+binding in our plan. Maybe a cheap pass to add (dead code analysis).
If it keeps growing, need to figure out why the frame isn't reused or why old ones live so long.

**Comment by antoniofilipovic** [comment] 2023-09-25 10:58
Seems issue is not fixed in 2.11, memory still isn't properly freed after the query is executed.

**Comment by DavIvek** [comment] 2023-10-09 12:11
Seems like the issue isn't only about the MERGE statement. A similar memory spike happens with CREATE.

**Comment by gitbuda** [comment] 2023-10-11 08:07
Research in progress under #1348

**Comment by DavIvek** [comment] 2023-10-13 21:41
Next python script will cause big memory spike and will create only one node: 
```
from gqlalchemy import Memgraph

memgraph = Memgraph("127.0.0.1", 7687)
batch_data = []
batch_size = 300
index = 1
address = 1000
memgraph.execute("CREATE INDEX ON :MyNode(address)")
for i in range(100000):
    s = f"s{str(index)}"
    query = f"MERGE ({s}:MyNode)"
    batch_data.append(query)
    index += 1
    address += 1

    if len(batch_data) >= batch_size:
        memgraph.execute("".join(batch_data))
        batch_data = []
```
After running this script memgraph will use 1.85 GB of memory and won't release it.

Also, when we change batch_size, the amount of allocated memory also changes. With a batch size of 1 memgraph uses around 650 MB, with a batch size of 300 it uses around 1.85 GB, and with a batch size of 500, it uses around 2.9 GB of memory. But the main thing is that memory isn't released.

![Screenshot from 2023-10-13 23-36-37](https://github.com/memgraph/memgraph/assets/88043717/98764f14-9c23-48e8-a4db-0ec0c308021b)

**Comment by DavIvek** [comment] 2023-10-20 19:05
Memgraph uses a plan cache to save plans so it can use already generated ones in future queries. We can define how long we want our plans to be saved with config flag --query-plan-cache-ttl. Memgraph is only evicting expired plans when we encounter the same plan again, which results in the majority of plans never being evicted. Also, what makes me so confident that the problem is in the plan cache is that by deleting these lines of code: plan_cache_access->insert({hash, plan}); in cypher_query_interpreter, we use 15x less memory.

**Closed** 2023-11-07 12:34 UTC
Labels: bug, Importance - I3, Effort - Medium, Severity - S3, memory, DX
